### PR TITLE
Add Austria as supported country

### PR DESCRIPTION
**Pull request by nwpr**

### CODE REVIEW

**Comment by Sholofly** [comment]
Thanks for your contribution!

**Comment by Sholofly** [comment]
The component in HA is updated with this change but maybe broken due to another change. Please let me know if you experience issues, you might be able to help me solve 'em

**Comment by nwpr** [comment]
It's broken; where did you find the personalization URL?
We need to add it for AT.

**Comment by Sholofly** [comment]
In the browser when you use the online player.


Op wo 26 aug. 2020 00:02 schreef Nikolaus Walther <notifications@github.com

**Pull request merged**
