### PR TITLE
Enable Telenet for BE and stop function

### PR DESCRIPTION
**Pull request by geertsmichael**

### CODE REVIEW

**Comment by geertsmichael** [comment]
Thanks, I finalized the Telenet integration and it's fully working now.
A summary of my changes:

- Authentication: Telenet is using a SSO system, so I had to do a chain of calls to get the OESP token.
- channels for Telenet are organized per location, which can also be fetched from the session call. I did not enable location based channels for other implementations (only Telenet)

**Comment by geertsmichael** [comment]
Thanks for merging, can you release a new version? And update the home assistant component?
Thanks in advance. Really nice project, thanks for all the effort

**Comment by Sholofly** [comment]
On my way, have some merging to do 👍

**Comment by Sholofly** [comment]
@geertsmichael It's done. Please update the component.

**Comment by geertsmichael** [comment]
It all works perfect. Is the Ziggo set-up also still working for you?

**Comment by Sholofly** [comment]
Yes, Do you see images and recordings in your component? Tested it with
another Belgian guy on Discord without seeing now playing information.

Op zo 6 dec. 2020 om 00:03 schreef Michaël <notifications@github.com>:

**Comment by geertsmichael** [comment]
Yes, I can also see the recordings and even start them. 
When started, the information about the playing episode is also visible.

**Pull request merged**
